In [1]:
import pandas as pd
import numpy as np


In [2]:
#nutrition of separate foods
nutrition_database=pd.read_csv("/home/jovyan/EEP153_Materials/Project4/NutritionalValuesandFDCCodesforEthiopia.csv")
#household characteristics by age brackets
households=pd.read_csv("/home/jovyan/EEP153_Materials/Project4/CopyofEthiopia-HHCharacteristics.csv")
#Requirements for family members
DRI=pd.read_csv("/home/jovyan/EEP153_Materials/Project4/DRI-Complete.csv")

#In DRI I created new rows for 51+ that combine expectations of 51-70 and 70+ in original by looking at population pyramids
#Looking at pregnancy rate 3.35% I also combined preg and lactation as part of the required intake for 
#women in range 14-50


consumption=pd.read_csv("/home/jovyan/EEP153_Materials/Project4/EthiopiaConsumption.csv")



/srv/app/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:


consumption=pd.read_csv("/home/jovyan/EEP153_Materials/Project4/EthiopiaConsumption.csv")


In [88]:
nutrition_database=pd.read_csv("/home/jovyan/EEP153_Materials/Project4/NutritionalValuesandFDCCodesforEthiopia.csv")

In [12]:
DRIcombine=DRI.drop(["Life Stage\nGroup", "Infants", "Children", "Males", "Females", "Pregnanc", "Lactation"], axis=1 ,)

In [5]:


IDlist=households["ID"]
households1=households.set_index("j")
households2=households.drop("j", axis=1)
household_nutrients={}
p=.0335 #pregnancy rate ethiopia
for j in range(len(jlist)):
    household_nutrients[j]=households2.iloc[j][1]*DRIcombine.loc[0]+households2.iloc[j][2]*DRIcombine.iloc[1]+households2.iloc[j][3]*DRIcombine.iloc[2] +households2.iloc[j][4]*DRIcombine.iloc[3] +households2.iloc[j][5]*DRIcombine.iloc[4]+households2.iloc[j][6]*DRIcombine.iloc[5]+households2.iloc[j][7]*DRIcombine.iloc[8]+households2.iloc[j][8]*DRIcombine.loc[0]+households2.iloc[j][9]*DRIcombine.iloc[1]+households2.iloc[j][10]*DRIcombine.iloc[9]+(1-2*p)*households2.iloc[j][11]*DRIcombine.iloc[10]+p*households2.iloc[j][11]*DRIcombine.iloc[16]+p*households2.iloc[j][11]*DRIcombine.iloc[19]+(1-2*p)*households2.iloc[j][12]*DRIcombine.iloc[11]+p*households2.iloc[j][12]*DRIcombine.iloc[17]+p*households2.iloc[j][12]*DRIcombine.iloc[20]+(1-2*p)*households2.iloc[j][13]*DRIcombine.iloc[12]+p*households2.iloc[j][13]*DRIcombine.iloc[18]+p*households2.iloc[j][13]*DRIcombine.iloc[21]+households2.iloc[j][14]*DRIcombine.iloc[15]
    

    

KeyError: 'ID'

In [3]:
household_nutrients
target_nutrients=pd.DataFrame.from_dict(household_nutrients)
target_nutrients.rename(IDlist, axis=1)

NameError: name 'household_nutrients' is not defined

In [5]:
#list of different units
consumption=consumption.fillna(0)
units=[]
concon=consumption["u"]
for i in concon: 
    if i not in units:
        units.append(i)
units

['Gram',
 'Kg',
 0,
 'Number',
 'Liter',
 'Cup',
 'Pack',
 'Roll',
 'Araba',
 'Pair',
 '40',
 'Cm',
 'Cubic Centimeter',
 'Tuba',
 'Box',
 'Other(Specify)',
 'Shekim',
 'Kilogram',
 'Medeb Small',
 'Esir Small',
 'Tasa/Tanika/Shember/Selemon Medium',
 'Piece/number Meduim',
 'Tasa/Tanika/Shember/Selemon Small',
 'Esir Medium',
 'Jog',
 'Tasa/Tanika/Shember/Selemon Large',
 'Medeb Medium',
 'Medeb Large',
 'Esir Large',
 'Piece/number small',
 'Sini Large',
 'Sini Small',
 'Birchiko Small',
 'Mili Liter',
 'Birchiko Meduim',
 'Piece/number Large',
 'Birchiko Large',
 'Kubaya Small',
 'Kubaya Meduim',
 'Kubaya Large',
 'Kunna/Mishe/Kefer/Enkib Small',
 'Kunna/Mishe/Kefer/Enkib Medium',
 'Festal Small',
 'Other (Specify)',
 'Kunna/Mishe/Kefer/Enkib Large',
 'Sahin Large',
 'Sahin Medium',
 'Festal Meduim',
 'Melekia',
 'Zorba/Akara \xa0  Medium',
 'Zorba/Akara \xa0  Small',
 'Quintal',
 'Zorba/Akara \xa0  Large',
 'Sahin Small',
 'Shekim Medium',
 'Kerchat/Kemba Small',
 'Madaberia/Nuse/S

In [59]:
DRIcombine

Calcium (mg/d)  Chromium (μg/d)  Copper (μg/d)  Fluoride (mg/d)  \
0            700.0             11.0          340.0              0.7   
1           1000.0             15.0          440.0              1.0   
2           1300.0             25.0          700.0              2.0   
3           1300.0             35.0          890.0              3.0   
4           1000.0             35.0          900.0              4.0   
5           1000.0             35.0          900.0              4.0   
6           1000.0             30.0          900.0              4.0   
7           1200.0             30.0          900.0              4.0   
8           1050.0             30.0          900.0              4.0   
9           1300.0             21.0          700.0              2.0   
10          1300.0             24.0          890.0              3.0   
11          1000.0             25.0          900.0              3.0   
12          1000.0             25.0          900.0              3.0   
13          1200.0             20.0          900.0              3.0   
14          1200.0             20.0          900.0              3.0   
15          1200.0             20.0          900.0              3.0   
16          1300.0             29.0         1000.0              3.0   
17          1000.0             30.0         1000.0              3.0   
18          1000.0             30.0         1000.0              3.0   
19          1300.0             44.0         1300.0              3.0   
20          1000.0             45.0         1300.0              3.0   
21          1000.0             45.0         1300.0              3.0   

    Iodine (μg/d)  Iron (mg/d)  Magnesium (mg/d)  Manganese (mg/d)  \
0            90.0          7.0              80.0               1.2   
1            90.0         10.0             130.0               1.5   
2           120.0          8.0             240.0               1.9   
3           150.0         11.0             410.0               2.2   
4           150.0          8.0             400.0               2.3   
5           150.0          8.0             420.0               2.3   
6           150.0          8.0             420.0               2.3   
7           150.0          8.0             420.0               2.3   
8           150.0          8.0             420.0               2.3   
9           120.0          8.0             240.0               1.6   
10          150.0         15.0             360.0               1.6   
11          150.0         18.0             310.0               1.8   
12          150.0         18.0             320.0               1.8   
13          150.0          8.0             320.0               1.8   
14          150.0          8.0             320.0               1.8   
15          150.0          8.0             320.0               1.8   
16          220.0         27.0             400.0               2.0   
17          220.0         27.0             350.0               2.0   
18          220.0         27.0             360.0               2.0   
19          290.0         10.0             360.0               2.6   
20          290.0          9.0             310.0               2.6   
21          290.0          9.0             320.0               2.6   

    lbdenum (μg/d)  Phosphorus (mg/d)       ...        \
0             17.0              460.0       ...         
1             22.0              500.0       ...         
2             34.0             1250.0       ...         
3             43.0             1250.0       ...         
4             45.0              700.0       ...         
5             45.0              700.0       ...         
6             45.0              700.0       ...         
7             45.0              700.0       ...         
8             45.0              700.0       ...         
9             34.0             1250.0       ...         
10            43.0             1250.0       ...         
11            45.0              700.0       ...         
12            45.0

In [4]:
#returns tuples (t, j) to act as a stamp for every household
marker=[]
for i in range(len(consumption["t"])):
    if (consumption["t"][i], consumption["j"][i]) not in marker:
        marker.append((consumption["t"][i], consumption["j"][i]))

#group creates tuples of households responding in acceptable units
acceptable_units={"Gram", "Kg", "Kilogram", "Litre", "Cup", "Milli Litre",  "Number", 0}
final_group=[]
consumption=consumption.fillna(0)
for n in marker:
    ind_frame1=consumption[consumption.t==n[0]]
    ind_frame2=ind_frame1[ind_frame1.j==n[1]]
    ind_measurements=ind_frame2["u"]
    ind_measurements=set(ind_measurements)
    if ind_measurements.issubset(acceptable_units):
        final_group.append(n)
        
#list of tuples every household as seen in dataset
full_IDs=[]
for j in range(len(consumption)):
    full_IDs.append((consumption["t"][j], consumption["j"][j]))

    
#to parse, we cannot use pandas values with tuoples but isin works with floats
#we now make new IDs that are divisions of original

single_value_IDs=[]
for i in range(len(full_IDs)):
    single_value_ID=full_IDs[i][1]/full_IDs[i][0]
    single_value_IDs.append(single_value_ID)

consumption["ID"]= single_value_ID

final_group_singles=[]
for i in range(len(final_group)):
    s=final_group[i][1]/final_group[i][0]
    final_group_singles.append(s)
    
marker_singles=[]
for i in range(len(marker)):
    f=marker[i][1]/marker[i][0]
    marker_singles.append(f)

#an ID is not in final group it is dropped from the new consumption table 
tf=[]
for i in range(len(single_value_IDs)):
    tf.append(({single_value_IDs[i]}).issubset(set(final_group_singles)))
consumption["tf"]=tf
consumption_new=consumption[consumption["tf"]==True]


consumption_new

t             j         u   Field Pea  Banana  Barley  Beef  Beer  \
0      2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
1      2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
2      2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
3      2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
4      2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
5      2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
6      2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
7      2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
8      2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
9      2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
10     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
11     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
12     2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
13     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
14     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
15     2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
16     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
17     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
18     2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
19     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
20     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
21     2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
22     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
23     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
24     2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
25     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
26     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
27     2011  1.010102e+12      Gram         0.0     0.0     0.0   0.0   0.0   
28     2011  1.010102e+12        Kg         0.0     0.0     0.0   0.0   0.0   
29     2011  1.010102e+12         0         0.0     0.0     0.0   0.0   0.0   
...     ...           ...       ...         ...     ...     ...   ...   ...   
50054  2015  1.408010e+13      Gram         0.0     0.0     0.0   0.0   0.0   
50055  2015  1.408010e+13  Kilogram         1.0     0.0     0.0   0.0   0.0   
50056  2015  1.408010e+13         0         0.0     0.0     0.0   0.0   0.0   
50220  2015  1.409030e+13      Gram         0.0     0.0     0.0   0.0   0.0   
50221  2015  1.409030e+13         0         0.0     0.0     0.0   0.0   0.0   
50377  2015  1.410060e+13  Kilogram         1.0     0.0     0.0   0.0   0.0   
50378  2015  1.410060e+13         0         0.0     0.0     0.0   0.0   0.0   
50422  2015  1.410060e+13      Gram         0.0     0.0     0.0   0.0   0.0   
50423  2015  1.410060e+13  Kilogram         0.5     0.0     0.0   0.0   0.0   
50424  2015  1.410060e+13         0         0.0     0.0     0.0   0.0   0.0   
51142  2015  1.501010e+13         0         0.0     0.0     0.0   0.0   0.0   
51143  2015  1.501010e+13         0         0.0     0.0     0.0   0.0   0.0   
51177  2015  1.501010e+13         0         0.0     0.0     0.0   0.0   0.0   
51187  2015  1.501010e+13         0         0.0     0.0     0.0   0.0   0.0   
51188  2015  1.501010e+13         0         0.0     0.0     0.0   0.0   0.0   
51539  2015  1.501020e+13      Gram         0.0     0.0     0.0   0.0   0.0   
51540  2015  1.501020e+13         0         0.0     0.0     0.0   0.0   0.0   
51859  2015  1.501020e+13      Gram         0.0     0.0     0.0   0.0   0.0   
51860  2015  1.501020e+13  Kilogram         0.0     0.0     

In [7]:
consumption_new=consumption_new[consumption_new.u != 0]
consumption_new=consumption_new.reset_index(drop=True)
consumption1=consumption_new.drop(["t", "j", "u", "ID", "tf"], axis=1, inplace=False).fillna(0)
numbers=[]
individual_units=consumption_new["u"]
for i in range(len(consumption_new["u"])): 
    if individual_units[i].startswith("N"):
        row=consumption1.loc[i]
        nonzeros=np.nonzero(row)
        numbers.append(nonzeros)


        
numbers                

[(array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([27]),),
 (array([13]),),
 (array([13]),),
 (array([13, 27]),),
 (array([13]),),
 (array([13, 27]),),
 (array([1]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([27]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([32, 53]),),
 (array([47]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([32]),),
 (array([42]),),
 (array([32]),),
 (array([42]),),
 (array([32]),),
 (array([32]),),
 (array([13]),),
 (array([49, 53, 56]),),
 (array([13]),),
 (array([27]),),
 (array([27]),),
 (array([13]),),
 (array([13]),),
 (array([1]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([1]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),

In [153]:
consumption1=consumption_new.drop(["t", "j", "u", "ID", "tf"], axis=1, inplace=False).fillna(0)
consumption1.iloc[, [1, 2, 9, 11, 13, 22, 27, 32, 42, 47, 49, 50, 53, 56]]

[(array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([27]),),
 (array([13]),),
 (array([13]),),
 (array([13, 27]),),
 (array([13]),),
 (array([13, 27]),),
 (array([1]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([27]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([32, 53]),),
 (array([47]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([32]),),
 (array([42]),),
 (array([32]),),
 (array([42]),),
 (array([32]),),
 (array([32]),),
 (array([13]),),
 (array([49, 53, 56]),),
 (array([13]),),
 (array([27]),),
 (array([27]),),
 (array([13]),),
 (array([13]),),
 (array([1]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([1]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),),
 (array([13]),

In [5]:
#what we iterate over
units={"Gram", "Kg", "Kilogram", "Litre", "Cup", "Milli Litre",  "Number"}

#discards 0 unit columns and resets index
consumption_new=consumption_new[consumption_new.u != 0]
consumption_new=consumption_new.reset_index(drop=True)


individual_units=consumption_new["u"]
consumption1=consumption_new.drop(["t", "j", "u", "ID", "tf"], axis=1, inplace=False).fillna(0)


consumption1=consumption1.drop(["Eggs"], axis=1, inplace=False)
#egg column are strings of numbers so we must change before continuing
eggs=[]
for i in range(len(consumption1)):
    eggs.append(float(consumption1.iloc[i][14]))

consumption1["Egg"]=eggs

for i in range(len(consumption_new["u"])):
    #kg or kilograms
    if individual_units[i].startswith("K") or individual_units[i].startswith("k"):
        consumption1.loc[i]=consumption1.loc[i]*10
    #grams
    elif individual_units[i].startswith("G") or individual_units[i].startswith("g"):
        consumption1.loc[i]=consumption1.loc[i]*.01
    #litre
    elif individual_units[i].startswith("L"):
        consumption1.loc[i]=np.array(consumption1.loc[i])*10
    #millilitre
    elif individual_units[i].startswith("M"):
        consumption1.loc[i]=np.array(consumption1.loc[i])*.01
    #cups 1 cup= 236.588 mL
    elif individual_units[i].startswith("C"):
        consumption1.loc[i]=np.array(consumption1.loc[i])*2.36588
    elif individual_units[i].startswith("N"):
        #Banana 120grams so 100grams is
        consumption1.iloc[i][1]=consumption1.iloc[i][1]*1.2
        #Barley cubic centimeter is .6 grams
        consumption1.iloc[i][2]= consumption1.iloc[i][2]*.006
        #Chat 100 to 300 g of fresh leaves are chewed to form a bolus we take 100g then as the normal
        consumption1.iloc[i][9]=consumption1.iloc[i][9]
        #Chickpea 1/8 cup is about 25g so 1 chickpea around 5 grams
        consumption1.iloc[i][11]=consumption1.iloc[i][11]*.05
        #Egg large egg is 56 grams is about middle in size tables on wiki
        consumption1.iloc[i][13]=consumption1.iloc[i][13]*55
        #Horsebean table spoon is about 7.5 grams,fits two
        consumption1.iloc[i][22]=consumption1.iloc[i][22]*.0375
        #Meat  is so broad we assume its the same as 1kg when purchased
        consumption1.iloc[i][27]=consumption1.iloc[i][27]*10
        #Onion medium onion. is about 110grams
        consumption1.iloc[i][32]=consumption1.iloc[i][32]*1.1
        #Potato range puts around 130
        consumption1.iloc[i][42]=consumption1.iloc[i][42]*130
        #Salt prob singular family put salt, we are going to set to same
        consumption1.iloc[i][47]=consumption1.iloc[i][47]
        #Sorghum 1000 grains. is 30 grams
        consumption1.iloc[i][49]=consumption1.iloc[i][49]*.3
        #Sugar same as salt
        consumption1.iloc[i][50]=consumption1.iloc[i][50]
        #Teff
        consumption1.iloc[i][53]=consumption1.iloc[i][53]
        #Wheat
        consumption1.iloc[i][56]=consumption1.iloc[i][56]
    

consumption1["u"]=consumption_new["u"]
consumption1["t"]=consumption_new["t"]
consumption1["j"]=consumption_new["j"]
consumption_final = consumption1.groupby(['j', 't'],as_index=False).sum()
#basically way to just get eggs back in the right spot
consumption_final=consumption_final[["t", "j",  "Field Pea", "Banana", "Barley", "Beef", "Beer", "Boye/Yam", "Bula",
"Butter/ghee", "Cassava", "Chat / Kat", "Cheese", "Chick Pea", "Coffee",
"Egg", "Field Pea", "Fish", "Goat & mutton meat","Godere", "Green chili pepper (kariya)",
"Greens (kale, cabbage, etc.)", "Ground nuts", "Haricot Beans", "Horsebeans",
"Kocho", "Lentils", "Linseed", "Maize", "Meat", "Milk", "Millet", "Niger Seed",
"Oils (processed)", "Onion", "Orange", "Pasta/Maccaroni", "Potato", "Poultry",
"Red pepper (berbere)","Salt","Soft drinks/Soda","Sorghum", "Sugar","Sweet potato",
"Tea", "Teff", "Tomato", "Wheat"]]

In [6]:
household

t             j  Field Pea  Banana  Barley  Beef  Beer  Boye/Yam  \
0     2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
1     2015  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
2     2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
3     2015  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
4     2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
5     2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
6     2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
7     2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
8     2015  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
9     2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
10    2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
11    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
12    2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
13    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
14    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
15    2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
16    2015  1.010102e+12        0.0     0.0     0.0  10.0   0.0       0.0   
17    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
18    2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
19    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
20    2013  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
21    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
22    2011  1.010102e+12        0.0     0.0     0.0   0.0   0.0       0.0   
23    2011  1.010201e+12        0.0     0.0     0.0   0.0   0.0       0.0   
24    2013  1.010201e+12        0.0     0.0     9.0   0.0   0.0       0.0   
25    2011  1.010201e+12        0.0     0.0     0.0   0.0   0.0       0.0   
26    2013  1.010201e+12        0.0     0.0     0.0   0.0   0.0       0.0   
27    2011  1.010201e+12        0.0     0.0     0.0   0.0   0.0       0.0   
28    2013  1.010201e+12        0.0     0.0     0.0   0.0   0.0       0.0   
29    2011  1.010201e+12        0.0     0.0     0.0   0.0   0.0       0.0   
...    ...           ...        ...     ...     ...   ...   ...       ...   
6682  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6683  2011  1.501020e+13        0.0    20.0    15.0   0.0   0.0       0.0   
6684  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6685  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6686  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6687  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6688  2015  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6689  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6690  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6691  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6692  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6693  2015  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6694  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6695  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6696  2015  1.501020e+13        0.0     5.0     0.0   0.0   0.0       0.0   
6697  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6698  2013  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6699  2015  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6700  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6701  2011  1.501020e+13        0.0     0.0     0.0   0.0   0.0       0.0   
6702 

In [13]:
DRIcombine=DRI.drop(["Life Stage\nGroup", "Infants", "Children", "Males", "Females", "Pregnanc", "Lactation"], axis=1 , inplace=False)

#float id for consumption
consumption_final["ID"]=consumption_final["j"]/consumption_final["t"]
households["ID"]=households["j"]/households["t"]
#float id for households
householdsIDs=households["ID"]
consumption_final_IDs=consumption_final["ID"]


#code to drop faulty observations with units confusing
tf=[]
for i in range(len(householdsIDs)):
    tf.append(({householdsIDs[i]}).issubset(set(consumption_final_IDs)))
households["tf"]=tf



households["tf"]=tf
households_new=households[households["tf"]==True]
households_new=households_new.drop(["tf"], axis=1, inplace=False).reset_index(drop=True)


#household1 is created to group in the same fashion, thus aligning DRIcombine with the household data
households1=households_new.groupby(['j', 't'],as_index=False).sum()
households1=households1.set_index(consumption_final_IDs)
#households2 drops descriptive
households2=households1.drop(["j", "ID", "t"], axis=1)
household_nutrients={}
p=.0335 #pregnancy rate ethiopia to increase accuracy
for j in range(len(consumption_final_IDs)):
    household_nutrients[j]=households2.iloc[j][0]*DRIcombine.loc[0]+households2.iloc[j][1]*DRIcombine.iloc[1]+households2.iloc[j][2]*DRIcombine.iloc[2] +households2.iloc[j][3]*DRIcombine.iloc[3] +households2.iloc[j][4]*DRIcombine.iloc[4]+households2.iloc[j][5]*DRIcombine.iloc[5]+households2.iloc[j][6]*DRIcombine.iloc[8]+households2.iloc[j][7]*DRIcombine.loc[0]+households2.iloc[j][8]*DRIcombine.iloc[1]+households2.iloc[j][9]*DRIcombine.iloc[9]+(1-2*p)*households2.iloc[j][10]*DRIcombine.iloc[10]+p*households2.iloc[j][10]*DRIcombine.iloc[16]+p*households2.iloc[j][10]*DRIcombine.iloc[19]+(1-2*p)*households2.iloc[j][11]*DRIcombine.iloc[11]+p*households2.iloc[j][11]*DRIcombine.iloc[17]+p*households2.iloc[j][11]*DRIcombine.iloc[20]+(1-2*p)*households2.iloc[j][12]*DRIcombine.iloc[12]+p*households2.iloc[j][12]*DRIcombine.iloc[18]+p*households2.iloc[j][12]*DRIcombine.iloc[21]+households2.iloc[j][13]*DRIcombine.iloc[15]
    

target_nutrients=pd.DataFrame.from_dict(household_nutrients)
target_nutrients

0       1            2            3     \
Calcium (mg/d)            8100.00000  1200.0   6900.00000   9900.00000   
Chromium (μg/d)            176.83750    20.0    146.83750    213.83750   
Copper (μg/d)             5446.75000   900.0   4356.75000   6216.75000   
Fluoride (mg/d)             18.00000     3.0     14.00000     19.70000   
Iodine (μg/d)              937.03500   150.0    757.03500   1117.03500   
Iron (mg/d)                 71.00000     8.0     60.00000     91.00000   
Magnesium (mg/d)          2081.34000   320.0   1591.34000   2381.34000   
Manganese (mg/d)            13.13350     1.8     11.03350     15.93350   
lbdenum (μg/d)             268.33500    45.0    214.33500    305.33500   
Phosphorus (mg/d)         6350.00000   700.0   5650.00000   7860.00000   
Selenium (μg/d)            330.67000    55.0    260.67000    380.67000   
Zinc (mg/d)                 59.23450     8.0     48.23450     70.23450   
Potassium (g/d)             31.61340     4.7     26.71340     38.41340   
Sodium (g/d)                10.00000     1.3      8.70000     12.40000   
Chloride (g/d)                   NaN     NaN          NaN          NaN   
Vitamin A (μg/d)          4822.44500   700.0   3822.44500   5722.44500   
Vitamin C (mg/d)           431.84250    75.0    326.84250    471.84250   
Vitamin D (μg/d)           106.30000    16.3     90.00000    135.00000   
Vitamin E (mg/d)            89.13400    15.0     70.13400    102.13400   
Vitamin K (μg/d)           550.00000    90.0    445.00000    620.00000   
Thiamin (mg/d)               7.02010     1.1      5.62010      8.22010   
Riboflavin (mg/d)            7.22680     1.1      5.72680      8.52680   
Niacin (mg/d)               92.23450    14.0     74.23450    108.23450   
Vitamin B6 (mg/d)            8.04355     1.5      6.24355      8.94355   
Folate (μg/d)             2410.05000   400.0   1910.05000   2760.05000   
Vitamin B12 (μg/d)          14.42010     2.4     11.42010     16.52010   
Pantothenic Acid (mg/d)     31.10050     5.0     25.10050     36.10050   
Biotin (μg/d)              167.16750    30.0    132.16750    182.16750   
Choline (mg/d)            2955.02500   425.0   2355.02500   3530.02500   
Total Water (L/d)           18.64690     2.7     15.04690     21.94690   
Carbohdrate (g/d)          914.18750   130.0    784.18750   1174.18750   
Total Fiber (g/d)          204.23450    21.0    176.23450    260.23450   
Energy (kcal)            15006.70000  1800.0  12606.70000  18606.70000   
Linoleic Acid (g/d)         88.06700    11.0     73.06700    108.06700   
α-Linolenic Acid (g/d)       8.51675     1.1      7.01675     10.41675   
Proteinb (g/d)             288.67500    46.0    224.67500    326.67500   

                           4       5           6          7          8     \
Calcium (mg/d)           1200.0  1200.0  4800.00000  3600.0000  3600.0000   
Chromium (μg/d)            20.0    20.0    87.83750    71.6750    71.6750   
Copper (μg/d)             900.0   900.0  3216.75000  2524.1700  2524.1700   
Fluoride (mg/d)             3.0     3.0    10.00000     8.0000     8.0000   
Iodine (μg/d)             150.0   150.0   547.03500   434.0700   434.0700   
Iron (mg/d)                 8.0     8.0    42.00000    41.2345    41.2345   
Magnesium (mg/d)          320.0   320.0  1111.34000   912.6800   912.6800   
Manganese (mg/d)            1.8     1.8     6.83350     5.0804     5.0804   
lbdenum (μg/d)             45.0    45.0   158.33500   122.8040   122.8040   
Phosphorus (mg/d)         700.0   700.0  3900.00000  3200.0000  3200.0000   
Selenium (μg/d)            55.0    55.0   190.67000   151.3400   151.3400   
Zinc (mg/d)                 8.0     8.0    32.23450    25.4690    25.4690   
Potassium (g/d)             4.7     4.7    18.41340    13.9268    13.9268   
Sodium (g/d)                1.3     1.3     5.80000     4.5000     4.5000   
Chloride (g/d)              NaN     NaN         NaN        NaN        NaN   
Vitamin A (μg/d)          700.0   700.0  2622.44500  2040.870

In [14]:
#shows that the IDs are still in the correct indexed arrangement when using group by
summation=0
for i in (range(len(consumption_final_IDs))):
    summation+=abs(households_new.groupby(['j', 't'],as_index=False).sum()["ID"][i]-consumption_final_IDs[i])
print(summation)

0.0


In [16]:
#drops descriptive columns and simplifies names
C=consumption_final.drop(["j", "t", "ID"], axis=1, inplace=False)
N=nutrition_database.drop(['Food', 'FDC Codes'], axis=1, inplace=False)

#double checks to convert everything to float
for j in range(len(N.columns)):
    for i in range(len(N["Energy (kcal)"])):
        N.iloc[i][j]=float(N.iloc[i][j])

/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


KeyboardInterrupt: 

In [44]:

column_names = [j for j in consumption_final["j"]]
health = pd.DataFrame(columns = column_names)
for i in range(len(C["Banana"])):
    nutrition_in_house=0
    for n in range(N.shape[0]):
        #sum of foods for one household
        nutrition_in_house += C.iloc[i][n]*np.array(N.T[N.T.columns[n]].fillna(0))
    health[i] = nutrition_in_house


In [63]:
summation=0
for i in (range(len(consumption_final_IDs))):
    summation+=abs(households_new.groupby(['j', 't', "ID"],as_index=False).sum()["ID"][i]-consumption_final_IDs[i])
print(summation)
        


0.0


In [74]:
#reorients and drops faulty NaN lines
health=health.T.dropna(how="all").T
health=health.set_index(N.columns)
health=health.rename_axis(consumption_final_IDs, axis=1)
health

/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Using 'rename_axis' to alter labels is deprecated. Use '.rename' instead
  after removing the cwd from sys.path.


5.022882e+08 5.012911e+08 5.022882e+08  \
Energy (kcal)                               4960         3325         2160   
Protein (g)                                   10       111.05        178.6   
Fiber, total dietary (g)                    21.5          116            7   
Folate, DFE (μg)                               0          740            0   
Calcium, Ca (mg)                             200          185          180   
Carbohydrate, by difference (g)           1188.6       322.25        55.55   
Iron, Fe (mg)                               6.75         20.6          6.4   
Magnesium, Mg (mg)                             0          165            0   
Niacin (mg)                                    0       11.245            0   
Phosphorus, P (mg)                             0          645            0   
Potassium, K (mg)                              0         1660            0   
Riboflavin (mg)                                0         1.45            0   
Thiamin (mg)                                   0        0.665            0   
Vitamin A, RAE (μg)                            0           85            0   
Vitamin B-12 (μg)                              0         3570            0   
Vitamin B-6 (mg)                               0         0.52            0   
Vitamin C, total ascorbic acid (mg)            0          147            0   
Vitamin E (alpha-tocopherol) (mg)              0        41.55            0   
Vitamin K (phylloquinone) (μg)                 0       209.25            0   
Zinc, Zn (mg)                                  0            5            0   

                                    5.012911e+08 5.022882e+08 5.017892e+08  \
Energy (kcal)                             3067.5      15977.5        20345   
Protein (g)                                301.3        484.4        590.6   
Fiber, total dietary (g)                     307          324        394.5   
Folate, DFE (μg)                            2960         1540         1740   
Calcium, Ca (mg)                             740         1105         1235   
Carbohydrate, by difference (g)            830.3      3404.53       4403.2   
Iron, Fe (mg)                               56.7       155.65       189.25   
Magnesium, Mg (mg)                           660         6765         8415   
Niacin (mg)                                44.98      158.765      195.645   
Phosphorus, P (mg)                          2580        12205        15095   
Potassium, K (mg)                           6640        16180        19810   
Riboflavin (mg)                              5.8         5.29         6.25   
Thiamin (mg)                                2.66       13.945       17.265   
Vitamin A, RAE (μg)                          340           85           85   
Vitamin B-12 (μg)                           7140            0            0   
Vitamin B-6 (mg)                            2.08        18.24        22.67   
Vitamin C, total ascorbic acid (mg)          331         18.5         18.5   
Vitamin E (alpha-tocopherol) (mg)           23.2         25.8         30.8   
Vitamin K (phylloquinone) (μg)               818        204.5        204.5   
Zinc, Zn (mg)                                 20         71.8         88.5   

                                    5.022882e+08 5.017892e+08 5.012911e+08  \
Energy (kcal)                              75360        69975      70482.5   
Protein (g)                               2309.6       2183.6      2328.97   
Fiber, total dietary (g)                 1492.25       1406.5      1547.75   
Folate, DFE (μg)                            5310         4740         4855   
Calcium, Ca (mg)                          3407.5         3185       3202.5   
Carbohydrate, by difference (g)          16537.2      15272.2      15588.9   
Iron, Fe (mg)                            730.725       693.25      720.025   
Magnesium, Mg (mg)                       34897.5        33165        33195   
Niacin (mg)                              791.347      74

NameError: name 'column' is not defined

In [57]:
households_new.sort_values("j")["ID"][1]

502288215.3242168

In [74]:
C=consumption_final.drop(["j", "t", "ID"], axis=1, inplace=False)
N=nutrition_database.drop(['Food', 'FDC Codes'], axis=1, inplace=False)

In [56]:
C.loc[6709]

Field Pea                        0.0
Banana                           0.0
Barley                           0.0
Beef                             0.0
Beer                             0.0
Boye/Yam                         0.0
Bula                             0.0
Butter/ghee                      0.0
Cassava                          0.0
Chat / Kat                       0.0
Cheese                           0.0
Chick Pea                        0.0
Coffee                           0.0
Egg                              0.0
Field Pea                        0.0
Fish                             0.0
Goat & mutton meat               0.0
Godere                           0.0
Green chili pepper (kariya)      0.0
Greens (kale, cabbage, etc.)     0.0
Ground nuts                      0.0
Haricot Beans                    0.0
Horsebeans                       0.0
Kocho                            0.0
Lentils                          0.0
Linseed                          0.0
Maize                            0.0
M

In [66]:
N.columns

Index(['Energy (kcal)', 'Protein (g)', 'Fiber, total dietary (g)',
       'Folate, DFE (μg)', 'Calcium, Ca (mg)',
       'Carbohydrate, by difference (g)', 'Iron, Fe (mg)',
       'Magnesium, Mg (mg)', 'Niacin (mg)', 'Phosphorus, P (mg)',
       'Potassium, K (mg)', 'Riboflavin (mg)', 'Thiamin (mg)',
       'Vitamin A, RAE (μg)', 'Vitamin B-12 (μg)', 'Vitamin B-6 (mg)',
       'Vitamin C, total ascorbic acid (mg)',
       'Vitamin E (alpha-tocopherol) (mg)', 'Vitamin K (phylloquinone) (μg)',
       'Zinc, Zn (mg)'],
      dtype='object')